local challenges = {
  'Pitch Black',
  'High Brow',
  'Head Trauma',
  'Darkness Falls',
  'The Tank',
  'Solar System',
  'Suicide King',
  'Cat Got Your Tongue',
  'Demo Man',
  'Cursed!',
  'Glass Cannon',
  'When Life Gives You Lemons',
  'Beans!',
  'It\'s in the Cards',
  'Slow Roll',
  'Computer Savvy',
  'Waka Waka',
  'The Host',
  'The Family Man',
  'Purist',
  'XXXXXXXXL',
  'SPEED!',
  'Blue Bomber',
  'PAY TO PLAY',
  'Have a Heart',
  'I RULE!',
  'BRAINS!',
  'PRIDE DAY!',
  'Onan\'s Streak',
  'The Guardian',
  'Backasswards',
  'Aprils Fool',
  'Pokey Mans',
  'Ultra Hard',
  'Pong',
  'Scat Man',
  'Bloody Mary',
  'Baptism by Fire',
  'Isaac\'s Awakening',
  'Seeing Double',
  'Pica Run',
  'Hot Potato',
  'Cantripped!',
  'Red Redemption',
  'DELETE THIS'
}

function GetChallengeName(id)
  return challenges[id] or 'iamerror'
end