local stageAssets = {
    {
        'basement',
        'cellar',
        'burning_basement',
        'basement_greed',
        'downpour',
        'dross'
    },
    {
        'basement',
        'cellar',
        'burning_basement',
        'caves_greed',
        'downpour',
        'dross'
    },
    {
        'caves',
        'catacombs',
        'flooded_caves',
        'depths_greed',
        'mines',
        'ashpit'
    },
    {
        'caves',
        'catacombs',
        'flooded_caves',
        'womb_greed',
        'mines',
        'ashpit'
    },
    {
        'depths',
        'necropolis',
        'dank_depths',
        'sheol_greed',
        'mausoleum',
        'gehenna'
    },
    {
        'depths',
        'necropolis',
        'dank_depths',
        'the_shop',
        'mausoleum',
        'gehenna'
    },
    {
        'womb',
        'utero',
        'scarred_womb',
        'ultra_greed',
        'corpse'
    },
    {
        'womb',
        'utero',
        'scarred_womb',
        '',
        'corpse'
    },
    {
        'blue_womb',
        'blue_womb',
        'blue_womb'
    },
    {
        'sheol',
        'cathedral'
    },
    {
        'dark_room',
        'chest'
    },
    {
        'void',
        'void'
    },
    {
        'home',
        'home'
    }
}

local characterAssets = {
    'isaac',
    'magdalene',
    'cain',
    'judas',
    'blue_baby',
    'eve',
    'samsom',
    'azazel',
    'lazarus',
    'eden',
    'the_lost',
    'lazarus2',
    'black_judas',
    'lilith',
    'keeper',
    'apollyon',
    'the_forgotten',
    'the_soul',
    'bethany',
    'jacob_and_esau',
    'iamerror',
    'tainted_isaac',
    'tainted_magdalene',
    'tainted_cain',
    'tainted_judas',
    'tainted_blue_baby',
    'tainted_eve',
    'tainted_samson',
    'tainted_azazel',
    'tainted_lazarus',
    'tainted_eden',
    'tainted_lost',
    'tainted_lilith',
    'tainted_keeper',
    'tainted_apollyon',
    'tainted_forgotten',
    'tainted_bethany',
    'tainted_jacob',
    'dead_tainted_lazarus',
    'tainted_jacob2',
    'tainted_soul',
}

function StageToDiscordAsset(stage, stageType)
    return stageAssets[stage][stageType + 1] or 'iamerror'
end

function CharacterToDiscordAsset(character)
    return characterAssets[character + 1] or 'iamerror'
end